[2023-02-07T09:12:07.544+0100] {__init__.py:50} DEBUG - Loading core task runner: StandardTaskRunner
[2023-02-07T09:12:07.552+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:12:07.553+0100] {base_task_runner.py:69} DEBUG - Planning to run as the  user
[2023-02-07T09:12:07.556+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> from DB
[2023-02-07T09:12:07.562+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2023-02-07T09:12:07.562+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:12:07.565+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:12:07.565+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2023-02-07T09:12:07.565+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:12:07.565+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]>
[2023-02-07T09:12:07.567+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2023-02-07T09:12:07.567+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2023-02-07T09:12:07.567+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2023-02-07T09:12:07.568+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2023-02-07T09:12:07.568+0100] {taskinstance.py:1093} DEBUG - <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]> dependency 'Trigger Rule' PASSED: True, The task instance did not have any upstream tasks.
[2023-02-07T09:12:07.570+0100] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [queued]>
[2023-02-07T09:12:07.570+0100] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:12:07.570+0100] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-07T09:12:07.570+0100] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-07T09:12:07.583+0100] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): top_topics> on 2023-02-07 08:09:06.301771+00:00
[2023-02-07T09:12:07.585+0100] {standard_task_runner.py:55} INFO - Started process 628 to run task
[2023-02-07T09:12:07.587+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'dagProcessusMetier', 'top_topics', 'manual__2023-02-07T08:09:06.301771+00:00', '--job-id', '2583', '--raw', '--subdir', 'DAGS_FOLDER/dagProcessusMetier.py', '--cfg-path', '/tmp/tmpfzmfv_d8']
[2023-02-07T09:12:07.588+0100] {standard_task_runner.py:83} INFO - Job 2583: Subtask top_topics
[2023-02-07T09:12:07.588+0100] {cli_action_loggers.py:65} DEBUG - Calling callbacks: [<function default_action_log at 0x7f7713f4c790>]
[2023-02-07T09:12:07.599+0100] {settings.py:407} DEBUG - Disposing DB connection pool (PID 628)
[2023-02-07T09:12:07.599+0100] {settings.py:266} DEBUG - Setting up DB connection pool (PID 628)
[2023-02-07T09:12:07.599+0100] {settings.py:339} DEBUG - settings.prepare_engine_args(): Using NullPool
[2023-02-07T09:12:07.615+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:12:07.616+0100] {task_command.py:388} INFO - Running <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [running]> on host TR.
[2023-02-07T09:12:07.617+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [running]> from DB
[2023-02-07T09:12:07.633+0100] {taskinstance.py:1017} DEBUG - previous_execution_date was called
[2023-02-07T09:12:07.634+0100] {taskinstance.py:848} DEBUG - Clearing XCom data
[2023-02-07T09:12:07.653+0100] {retries.py:80} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2023-02-07T09:12:07.656+0100] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=thomas
AIRFLOW_CTX_DAG_ID=dagProcessusMetier
AIRFLOW_CTX_TASK_ID=top_topics
AIRFLOW_CTX_EXECUTION_DATE=2023-02-07T08:09:06.301771+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-07T08:09:06.301771+00:00
[2023-02-07T09:12:07.656+0100] {__init__.py:117} DEBUG - Preparing lineage inlets and outlets
[2023-02-07T09:12:07.657+0100] {__init__.py:155} DEBUG - inlets: [], outlets: []
[2023-02-07T09:12:07.657+0100] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/tr/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/tr/airflow/dags/dagProcessusMetier.py", line 298, in top_topics
    K = kwargs['params']['K']
KeyError: 'K'
[2023-02-07T09:12:07.657+0100] {taskinstance.py:769} DEBUG - Refreshing TaskInstance <TaskInstance: dagProcessusMetier.top_topics manual__2023-02-07T08:09:06.301771+00:00 [running]> from DB
[2023-02-07T09:12:07.659+0100] {taskinstance.py:2241} DEBUG - Task Duration set to 0.093791
[2023-02-07T09:12:07.659+0100] {taskinstance.py:1329} DEBUG - Clearing next_method and next_kwargs.
[2023-02-07T09:12:07.659+0100] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=dagProcessusMetier, task_id=top_topics, execution_date=20230207T080906, start_date=20230207T081207, end_date=20230207T081207
[2023-02-07T09:12:07.670+0100] {cli_action_loggers.py:83} DEBUG - Calling callbacks: []
[2023-02-07T09:12:07.670+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 2583 for task top_topics ('K'; 628)
[2023-02-07T09:12:07.680+0100] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-07T09:12:07.687+0100] {dagrun.py:688} DEBUG - number of tis tasks for <DagRun dagProcessusMetier @ 2023-02-07 08:09:06.301771+00:00: manual__2023-02-07T08:09:06.301771+00:00, state:running, queued_at: 2023-02-07 08:09:06.318179+00:00. externally triggered: True>: 0 task(s)
[2023-02-07T09:12:07.687+0100] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
